# Generated by Django 6.0.6 on 2026-06-18 09:00

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('original_file', models.FileField(upload_to=videos.models.video_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=videos.models.thumbnail_upload_path)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('hls_480p_path', models.CharField(blank=True, max_length=500)),
                ('hls_720p_path', models.CharField(blank=True, max_length=500)),
                ('hls_1080p_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
