# Generated by Django 6.0.6 on 2026-06-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
    ]
